const crypto=require('crypto');
const fs=require('fs');
const path=require('path');
const BRIDGE_SCHEMA_VERSION='local_mapping_bridge_v2';
const PROCESSOR_VERSION='range_library_backend_confirmed_v2';
const CONFIRMED='CONFIRMED';
const RESPONSE_INVALID='RESPONSE_INVALID';
const EDIT_KINDS=new Set(['structural_range','structural_event']);
const now=()=>new Date().toISOString();
function ordered(v){if(Array.isArray(v))return v.map(ordered);if(v&&typeof v==='object')return Object.keys(v).sort().reduce((o,k)=>(o[k]=ordered(v[k]),o),{});return v}
const canonicalJson=(v)=>JSON.stringify(ordered(v));
function normalizeEditRequest(r={}){const kind=String(r.kind||'').trim(),source=String(r.source||'').trim();if(!EDIT_KINDS.has(kind))throw new Error(`local mapping bridge does not accept edit kind: ${kind||'missing'}`);if(!source)throw new Error('local mapping bridge requires edit source');const envelope={schema_version:BRIDGE_SCHEMA_VERSION,kind,source,payload:r.payload&&typeof r.payload==='object'?r.payload:{},path_params:r.pathParams&&typeof r.pathParams==='object'?r.pathParams:{}};const payloadJson=canonicalJson(envelope),payloadSha256=crypto.createHash('sha256').update(payloadJson).digest('hex');return{editId:String(r.editId||`fxedit_${payloadSha256}`),payloadJson,payloadSha256,envelope}}
const CREATE=`CREATE TABLE IF NOT EXISTS local_mapping_edits(edit_id TEXT PRIMARY KEY,schema_version TEXT NOT NULL,edit_kind TEXT NOT NULL,edit_source TEXT NOT NULL,payload_json TEXT NOT NULL,payload_sha256 TEXT NOT NULL,status TEXT NOT NULL,attempt_count INTEGER NOT NULL DEFAULT 0,created_at_utc TEXT NOT NULL,updated_at_utc TEXT NOT NULL,processing_started_at_utc TEXT,processed_at_utc TEXT,last_error TEXT,result_json TEXT,processor_version TEXT,python_database_path TEXT,backend_status TEXT NOT NULL DEFAULT 'UNCONFIRMED',backend_attempt_count INTEGER NOT NULL DEFAULT 0,backend_response_json TEXT,backend_confirmed_payload_json TEXT,backend_confirmed_payload_sha256 TEXT,backend_http_status INTEGER,backend_error TEXT,backend_confirmed_at_utc TEXT,backend_range_id TEXT,backend_event_id TEXT);CREATE UNIQUE INDEX IF NOT EXISTS idx_local_mapping_edits_payload ON local_mapping_edits(payload_sha256);CREATE INDEX IF NOT EXISTS idx_local_mapping_edits_status ON local_mapping_edits(status,updated_at_utc);`;
const MIG={backend_status:"TEXT NOT NULL DEFAULT 'UNCONFIRMED'",backend_attempt_count:'INTEGER NOT NULL DEFAULT 0',backend_response_json:'TEXT',backend_confirmed_payload_json:'TEXT',backend_confirmed_payload_sha256:'TEXT',backend_http_status:'INTEGER',backend_error:'TEXT',backend_confirmed_at_utc:'TEXT',backend_range_id:'TEXT',backend_event_id:'TEXT'};
function schema(db){db.exec(CREATE);const cols=new Set(db.prepare('PRAGMA table_info(local_mapping_edits)').all().map(r=>String(r.name)));for(const[n,d]of Object.entries(MIG))if(!cols.has(n))db.exec(`ALTER TABLE local_mapping_edits ADD COLUMN ${n} ${d}`);db.exec("CREATE INDEX IF NOT EXISTS idx_local_mapping_edits_backend ON local_mapping_edits(backend_status,status,updated_at_utc)")}
function open(databasePath){const p=path.resolve(databasePath);fs.mkdirSync(path.dirname(p),{recursive:true});const{DatabaseSync}=require('node:sqlite'),db=new DatabaseSync(p);db.exec('PRAGMA journal_mode=WAL');db.exec('PRAGMA synchronous=FULL');db.exec('PRAGMA busy_timeout=60000');schema(db);return{db,p}}
function parse(v){if(!v)return null;try{return JSON.parse(String(v))}catch{return{raw:String(v)}}}
function state(row,p){if(!row)return null;const status=String(row.status||'AWAITING_BACKEND').toUpperCase(),publicState=status==='PROCESSED'?'SUCCESS':['BACKEND_REJECTED','BACKEND_CONFIRMATION_INCOMPLETE','PYTHON_FAILED'].includes(status)?'FAILED':'PENDING',pythonPath=row.python_database_path?path.resolve(String(row.python_database_path)):null;return{ok:publicState!=='FAILED',saved:true,state:publicState,status,editId:String(row.edit_id),duplicate:false,backendStatus:String(row.backend_status||'UNCONFIRMED'),backendAttemptCount:Number(row.backend_attempt_count||0),backendResponse:parse(row.backend_response_json),backendConfirmedPayload:parse(row.backend_confirmed_payload_json),backendHttpStatus:row.backend_http_status??null,backendRangeId:row.backend_range_id||null,backendEventId:row.backend_event_id||null,backendError:row.backend_error||undefined,attemptCount:Number(row.attempt_count||0),databasePath:p,electronDatabasePath:p,pythonDatabasePath:pythonPath,sameDatabasePath:pythonPath?pythonPath===p:null,processorVersion:row.processor_version||null,error:row.last_error||row.backend_error||undefined,result:parse(row.result_json),createdAt:row.created_at_utc,updatedAt:row.updated_at_utc,backendConfirmedAt:row.backend_confirmed_at_utc||null,processedAt:row.processed_at_utc||null}}
function responseValue(r,keys){for(const c of[r,r?.data,r?.range,r?.event,r?.data?.range,r?.data?.event])if(c&&typeof c==='object')for(const k of keys)if(c[k]!==undefined&&c[k]!==null&&c[k]!=='')return c[k]}
function extractBackendAssignedId(kind,r){const v=kind==='structural_range'?responseValue(r,['range_id','rangeId','id']):responseValue(r,['event_id','eventId','id']);if(v===undefined)throw new Error(`backend success did not return a final ${kind==='structural_range'?'range_id':'event_id'}`);return String(v)}
function buildBackendConfirmedEnvelope(row,r){const instruction=JSON.parse(String(row.payload_json)),original=instruction.payload&&typeof instruction.payload==='object'?instruction.payload:{},id=extractBackendAssignedId(String(row.edit_kind),r),payload={...original,backend_confirmed:true,local_edit_id:String(row.edit_id),source_record_id:id,backend_response:r};if(row.edit_kind==='structural_range'){payload.backend_range_id=id;payload.range_id=id}else{payload.backend_event_id=id;payload.event_id=id}for(const k of['case_ref','raw_case_id','case_id','symbol','active_range_id','parent_range_id','range_id'])if(payload[k]===undefined||payload[k]===null||payload[k]===''){const v=responseValue(r,[k]);if(v!==undefined)payload[k]=v}return{schema_version:BRIDGE_SCHEMA_VERSION,kind:String(row.edit_kind),source:String(row.edit_source),payload,original_payload:original,backend_response:r}}
function createLocalMappingStore({databasePath}={}){if(!databasePath)throw new Error('databasePath is required');const{db,p}=open(databasePath);let closed=false;const guard=()=>{if(closed)throw new Error('local mapping store is closed')},row=id=>(guard(),db.prepare('SELECT * FROM local_mapping_edits WHERE edit_id=?').get(String(id))),getStatus=id=>state(row(id),p);
function saveInstruction(r){guard();const n=normalizeEditRequest(r),t=now(),result=db.prepare("INSERT OR IGNORE INTO local_mapping_edits(edit_id,schema_version,edit_kind,edit_source,payload_json,payload_sha256,status,attempt_count,created_at_utc,updated_at_utc,backend_status,backend_attempt_count)VALUES(?,?,?,?,?,?,'AWAITING_BACKEND',0,?,?,'UNCONFIRMED',0)").run(n.editId,BRIDGE_SCHEMA_VERSION,n.envelope.kind,n.envelope.source,n.payloadJson,n.payloadSha256,t,t),saved=row(n.editId)||db.prepare('SELECT * FROM local_mapping_edits WHERE payload_sha256=?').get(n.payloadSha256),out=state(saved,p);out.duplicate=Number(result.changes||0)===0;return out}
function recordBackendFailure(id,d={}){const current=row(id);if(!current)throw new Error(`local mapping edit not found: ${id}`);if([CONFIRMED,RESPONSE_INVALID].includes(String(current.backend_status)))return getStatus(id);const error=String(d.error||'Backend structural save failed');db.prepare("UPDATE local_mapping_edits SET status='BACKEND_REJECTED',backend_status='REJECTED',backend_attempt_count=backend_attempt_count+1,backend_response_json=?,backend_http_status=?,backend_error=?,last_error=?,updated_at_utc=? WHERE edit_id=? AND backend_status NOT IN('CONFIRMED','RESPONSE_INVALID')").run(d.response===undefined?null:canonicalJson(d.response),d.httpStatus??null,error,error,now(),String(id));return getStatus(id)}
function recordBackendSuccess(id,r,http=200){const current=row(id);if(!current)throw new Error(`local mapping edit not found: ${id}`);if([CONFIRMED,RESPONSE_INVALID].includes(String(current.backend_status)))return getStatus(id);const t=now();let envelope,finalId;try{finalId=extractBackendAssignedId(String(current.edit_kind),r);envelope=buildBackendConfirmedEnvelope(current,r)}catch(e){const error=e?.message||String(e);db.prepare("UPDATE local_mapping_edits SET status='BACKEND_CONFIRMATION_INCOMPLETE',backend_status='RESPONSE_INVALID',backend_attempt_count=backend_attempt_count+1,backend_response_json=?,backend_http_status=?,backend_error=?,last_error=?,backend_confirmed_at_utc=NULL,backend_confirmed_payload_json=NULL,backend_confirmed_payload_sha256=NULL,backend_range_id=NULL,backend_event_id=NULL,updated_at_utc=? WHERE edit_id=? AND backend_status NOT IN('CONFIRMED','RESPONSE_INVALID')").run(canonicalJson(r),http,error,error,t,String(id));return getStatus(id)}const json=canonicalJson(envelope),hash=crypto.createHash('sha256').update(json).digest('hex');db.prepare("UPDATE local_mapping_edits SET status='PYTHON_PENDING',backend_status='CONFIRMED',backend_attempt_count=backend_attempt_count+1,backend_response_json=?,backend_confirmed_payload_json=?,backend_confirmed_payload_sha256=?,backend_http_status=?,backend_error=NULL,last_error=NULL,backend_confirmed_at_utc=?,backend_range_id=?,backend_event_id=?,updated_at_utc=? WHERE edit_id=? AND backend_status NOT IN('CONFIRMED','RESPONSE_INVALID')").run(canonicalJson(r),json,hash,http,t,current.edit_kind==='structural_range'?finalId:null,current.edit_kind==='structural_event'?finalId:null,t,String(id));return getStatus(id)}
function markPythonFailed(id,error){db.prepare("UPDATE local_mapping_edits SET status='PYTHON_FAILED',last_error=?,updated_at_utc=?,processor_version=COALESCE(processor_version,?),python_database_path=COALESCE(python_database_path,?) WHERE edit_id=? AND backend_status='CONFIRMED' AND status!='PROCESSED'").run(String(error||'Python processing failed'),now(),PROCESSOR_VERSION,p,String(id));return getStatus(id)}
function markPythonPending(id){db.prepare("UPDATE local_mapping_edits SET status='PYTHON_PENDING',last_error=NULL,processing_started_at_utc=NULL,updated_at_utc=? WHERE edit_id=? AND backend_status='CONFIRMED' AND status!='PROCESSED'").run(now(),String(id));return getStatus(id)}
function recoverInterrupted(){return Number(db.prepare("UPDATE local_mapping_edits SET status='PYTHON_PENDING',last_error='Recovered after application restart while Python was processing.',processing_started_at_utc=NULL,updated_at_utc=? WHERE status='PYTHON_PROCESSING' AND backend_status='CONFIRMED'").run(now()).changes||0)}
function listRetryable(limit=100){const n=Math.max(1,Math.min(Number(limit)||100,1000));return db.prepare("SELECT * FROM local_mapping_edits WHERE backend_status='CONFIRMED' AND status IN('PYTHON_PENDING','PYTHON_FAILED') ORDER BY backend_confirmed_at_utc,created_at_utc LIMIT ?").all(n).map(r=>state(r,p))}
function count(){return Number(db.prepare('SELECT COUNT(*) n FROM local_mapping_edits').get()?.n||0)}function close(){if(!closed){db.close();closed=true}}return{databasePath:p,saveInstruction,getStatus,recordBackendFailure,recordBackendSuccess,markPythonFailed,markPythonPending,recoverInterrupted,listRetryable,count,close}}
function resolveRangeLibraryPythonRoot(explicit){const candidates=[explicit,process.env.FXTM_RANGE_LIBRARY_PYTHON_ROOT,path.resolve(process.cwd(),'../python'),path.resolve(process.cwd(),'python'),path.resolve(__dirname,'../../python'),process.resourcesPath].filter(Boolean);for(const c of candidates){const root=path.resolve(String(c));if(fs.existsSync(path.join(root,'range_library_memory','local_edit_bridge.py')))return root}return path.resolve(String(candidates[0]||path.resolve(process.cwd(),'../python')))}
async function runPythonProcessor({editId,databasePath,pythonRoot,pythonPath,spawnFn,timeoutMs}){const{spawnLocalPythonScript}=require('./localPythonRunner.cjs'),root=resolveRangeLibraryPythonRoot(pythonRoot),exe=pythonPath||process.env.FXTM_PYTHON||process.env.PYTHON||'python';return spawnLocalPythonScript({script:'range_library_memory.local_edit_bridge',pythonPath:exe,args:['-m','range_library_memory.local_edit_bridge','process','--db-path',path.resolve(databasePath),'--edit-id',String(editId),'--json'],cwd:root,env:{...process.env,PYTHONPATH:root,PYTHONUNBUFFERED:'1',FXTM_RANGE_LIBRARY_MEMORY_DB:path.resolve(databasePath)}},{spawnFn,timeoutMs:timeoutMs||60000,parse:s=>JSON.parse(String(s).trim())})}
function createLocalMappingBridgeService(options={}){const store=createLocalMappingStore({databasePath:options.databasePath}),processor=options.processor||runPythonProcessor,inFlight=new Map();store.recoverInterrupted();async function processEdit(id){const key=String(id);if(inFlight.has(key))return inFlight.get(key);const promise=(async()=>{const before=store.getStatus(key);if(!before)throw new Error(`local mapping edit not found: ${key}`);if(before.state==='SUCCESS'||before.backendStatus!==CONFIRMED)return before;const result=await processor({editId:key,databasePath:store.databasePath,pythonRoot:options.pythonRoot,pythonPath:options.pythonPath,spawnFn:options.spawnFn,timeoutMs:options.timeoutMs});if(!result?.ok)return store.markPythonFailed(key,result?.error||result?.stderr||'Python processing failed');const after=store.getStatus(key);if(!after||['PYTHON_PENDING','PYTHON_FAILED','PYTHON_PROCESSING'].includes(after.status))return store.markPythonFailed(key,'Python exited without completing the confirmed edit state.');return after})().finally(()=>inFlight.delete(key));inFlight.set(key,promise);return promise}async function prepare(r){try{return store.saveInstruction(r)}catch(e){return{ok:false,saved:false,state:'FAILED',databasePath:store.databasePath,electronDatabasePath:store.databasePath,pythonDatabasePath:null,sameDatabasePath:null,error:e?.message||String(e)}}}async function backendSucceeded(id,r,http){const confirmation=store.recordBackendSuccess(id,r,http);if(confirmation.backendStatus!==CONFIRMED)return confirmation;return confirmation.state==='SUCCESS'?confirmation:processEdit(id)}const backendFailed=(id,d)=>store.recordBackendFailure(id,d);async function retry(id){const current=store.getStatus(id);if(!current)return{ok:false,saved:false,state:'FAILED',error:'edit not found'};if(current.state==='SUCCESS'||current.backendStatus!==CONFIRMED)return current;store.markPythonPending(id);return processEdit(id)}async function resumePending(limit=100){const results=[];for(const item of store.listRetryable(limit))results.push(await processEdit(item.editId));return{ok:true,resumed:results.length,results,databasePath:store.databasePath}}const getStatus=id=>store.getStatus(id)||{ok:false,saved:false,state:'FAILED',error:'edit not found'};return{store,prepare,submit:prepare,backendSucceeded,backendFailed,processEdit,retry,resumePending,getStatus,getPaths:()=>({ok:true,databasePath:store.databasePath,electronDatabasePath:store.databasePath,rangeLibraryPythonRoot:resolveRangeLibraryPythonRoot(options.pythonRoot)}),close:()=>store.close()}}
let defaultService=null;function defaultRangeLibraryDatabasePath(){const{app}=require('electron');return path.join(app.getPath('documents'),'FXTM_Research','range_library_memory.sqlite3')}function service(){if(!defaultService)defaultService=createLocalMappingBridgeService({databasePath:defaultRangeLibraryDatabasePath()});return defaultService}function registerLocalMappingBridgeIpc(){const{ipcMain,app}=require('electron'),s=service();ipcMain.handle('local-mapping:submit',(_e,r)=>s.prepare(r||{}));ipcMain.handle('local-mapping:backend-succeeded',(_e,a)=>s.backendSucceeded(a?.editId,a?.backendResponse,a?.httpStatus));ipcMain.handle('local-mapping:backend-failed',(_e,a)=>s.backendFailed(a?.editId,a||{}));ipcMain.handle('local-mapping:get-status',(_e,a)=>s.getStatus(a?.editId));ipcMain.handle('local-mapping:retry',(_e,a)=>s.retry(a?.editId));ipcMain.handle('local-mapping:get-paths',()=>s.getPaths());ipcMain.handle('local-mapping:resume-pending',(_e,a)=>s.resumePending(a?.limit));app.once('will-quit',closeLocalMappingBridge);setImmediate(()=>s.resumePending().catch(e=>console.error(`[local-mapping] pending resume failed: ${e?.message||String(e)}`)))}function closeLocalMappingBridge(){if(defaultService){defaultService.close();defaultService=null}}
module.exports={BRIDGE_SCHEMA_VERSION,PROCESSOR_VERSION,canonicalJson,normalizeEditRequest,createLocalMappingStore,createLocalMappingBridgeService,resolveRangeLibraryPythonRoot,defaultRangeLibraryDatabasePath,runPythonProcessor,registerLocalMappingBridgeIpc,closeLocalMappingBridge,buildBackendConfirmedEnvelope,extractBackendAssignedId};
