from __future__ import annotations

import re
from pathlib import Path

TARGET = Path("python/range_library_memory/parent_conflict_resolver.py")


def replace_once(text: str, pattern: str, replacement: str, label: str) -> str:
    updated, count = re.subn(pattern, replacement, text, count=1, flags=re.S)
    if count != 1:
        raise RuntimeError(f"{label}: expected one replacement, got {count}")
    return updated


text = TARGET.read_text(encoding="utf-8")

text = replace_once(
    text,
    r"def resolve_parent_conflicts\(.*?\n\n\ndef summarize_parent_conflicts",
    'def resolve_parent_conflicts(\n    db_path: str | Path,\n    *,\n    case_ref: str | None = None,\n    daily_source_id: str | None = None,\n) -> dict[str, Any]:\n    """Rebuild Daily to Weekly relationships using derived Weekly lifecycle truth.\n\n    Raw mapping remains untouched. A raw explicit parent or the currently selected\n    relationship is treated as preferred chart context. It is confirmed only when\n    case, symbol, price, range-span chronology, and the best available Weekly\n    lifecycle agree. A preferred parent is never silently replaced.\n    """\n\n    path = init_schema(db_path)\n    filters = {\n        "case_ref": case_ref,\n        "daily_source_id": str(daily_source_id) if daily_source_id else None,\n    }\n    timestamp = utc_now()\n    with connect(path) as connection:\n        dailies = load_latest_ranges(connection, "DAILY")\n        weeklies = load_latest_ranges(connection, "WEEKLY")\n        lifecycles = load_latest_weekly_lifecycles(connection)\n        existing = load_latest_relationships(connection)\n        selected = [\n            daily\n            for daily in dailies\n            if (case_ref is None or daily.row.case_ref == case_ref)\n            and (daily_source_id is None or daily.row.source_record_id == str(daily_source_id))\n        ]\n        selected_ids = {daily.row.source_record_id for daily in selected}\n        rows = [\n            resolve_daily(\n                daily,\n                weeklies,\n                lifecycles,\n                existing.get(daily.row.source_record_id),\n                timestamp=timestamp,\n            )\n            for daily in selected\n        ]\n        clear_selected_relationships(connection, selected_ids)\n        for row in rows:\n            insert_relationship(connection, row)\n        connection.commit()\n    return build_summary(filters, rows)\n\n\ndef summarize_parent_conflicts',
    "resolve_parent_conflicts",
)

text = replace_once(
    text,
    r"def resolve_daily\(.*?\n\n\ndef resolve_explicit",
    'def resolve_daily(\n    daily: RangeSnapshot,\n    weeklies: list[RangeSnapshot],\n    lifecycles: dict[str, LifecycleSnapshot],\n    existing: sqlite3.Row | None,\n    *,\n    timestamp: str,\n) -> dict[str, Any]:\n    compatible: list[CandidateAssessment] = []\n    ambiguous: list[CandidateAssessment] = []\n    assessments: dict[str, CandidateAssessment] = {}\n\n    for weekly in weeklies:\n        assessment = assess_candidate(daily, weekly, lifecycles.get(weekly.row.source_record_id))\n        assessments[weekly.row.source_record_id] = assessment\n        if assessment.status == COMPATIBLE:\n            compatible.append(assessment)\n        elif assessment.status == AMBIGUOUS:\n            ambiguous.append(assessment)\n\n    raw_explicit_id = daily.row.explicit_parent_id\n    existing_parent_id = None\n    if (\n        not raw_explicit_id\n        and existing is not None\n        and str(existing["link_status"] or "").upper() in {VALID, NEEDS_REVIEW}\n        and existing["parent_range_id"] is not None\n    ):\n        existing_parent_id = str(existing["parent_range_id"])\n\n    preferred_id = str(raw_explicit_id or existing_parent_id or "")\n    if preferred_id:\n        preferred_daily = daily\n        if not raw_explicit_id:\n            preferred_daily = RangeSnapshot(\n                replace(daily.row, explicit_parent_id=preferred_id),\n                daily.formation_time,\n            )\n        result = resolve_explicit(\n            preferred_daily,\n            assessments.get(preferred_id),\n            compatible,\n            ambiguous,\n            timestamp=timestamp,\n        )\n        if existing_parent_id and not raw_explicit_id:\n            source = str(result["link_source"])\n            if source == "resolver_explicit":\n                result["link_source"] = "resolver_existing"\n            elif source == "resolver_explicit_lifecycle":\n                result["link_source"] = "resolver_existing_lifecycle"\n            result["notes"] = str(result["notes"]).replace(\n                "Explicit Weekly parent",\n                "Existing Weekly parent",\n            ).replace(\n                "Explicit parent",\n                "Existing parent",\n            )\n        return result\n\n    return resolve_inferred(\n        daily,\n        compatible,\n        ambiguous,\n        timestamp=timestamp,\n    )\n\n\ndef resolve_explicit',
    "resolve_daily",
)

text = replace_once(
    text,
    r"def assess_candidate\(.*?\n\n\ndef effective_parent_row",
    'def assess_candidate(\n    daily: RangeSnapshot,\n    weekly: RangeSnapshot,\n    lifecycle: LifecycleSnapshot | None,\n) -> CandidateAssessment:\n    reasons: list[str] = []\n    if weekly.row.case_ref != daily.row.case_ref:\n        reasons.append("case mismatch")\n    if weekly.row.symbol != daily.row.symbol:\n        reasons.append("symbol mismatch")\n    if reasons:\n        return CandidateAssessment(\n            weekly,\n            effective_parent_row(weekly.row, lifecycle),\n            INCOMPATIBLE,\n            tuple(reasons),\n            lifecycle_source(lifecycle),\n        )\n\n    if not prices_overlap(weekly.row, daily.row):\n        reasons.append("price does not overlap")\n\n    parent_effective = effective_parent_row(weekly.row, lifecycle)\n    parent_start = parse_time(parent_effective.start_time)\n    parent_cutoff = parse_time(parent_effective.inactive_from_time)\n    child_start = parse_time(daily.row.start_time or daily.formation_time)\n    child_end = parse_time(daily.row.end_time or daily.formation_time)\n\n    if child_start is None or child_end is None:\n        reasons.append("Daily range span is incomplete")\n    if parent_start is None:\n        reasons.append("Weekly formation time missing")\n    if child_end is not None and parent_start is not None and child_end < parent_start:\n        reasons.append("Daily ended before Weekly formed")\n    if child_start is not None and parent_cutoff is not None and child_start > parent_cutoff:\n        reasons.append("Daily started after Weekly became inactive")\n\n    if reasons:\n        return CandidateAssessment(\n            weekly,\n            parent_effective,\n            INCOMPATIBLE,\n            tuple(reasons),\n            lifecycle_source(lifecycle),\n        )\n\n    if inactive_lifecycle_is_ambiguous(parent_effective, lifecycle):\n        return CandidateAssessment(\n            weekly,\n            parent_effective,\n            AMBIGUOUS,\n            ("inactive Weekly has no trustworthy lifecycle cutoff",),\n            lifecycle_source(lifecycle),\n        )\n\n    return CandidateAssessment(\n        weekly,\n        parent_effective,\n        COMPATIBLE,\n        (),\n        lifecycle_source(lifecycle),\n    )\n\n\ndef effective_parent_row',
    "assess_candidate",
)

text = replace_once(
    text,
    r"def snapshot_from_row\(.*?\n\n\ndef load_latest_weekly_lifecycles",
    'def snapshot_from_row(row: dict[str, Any]) -> RangeSnapshot:\n    payload = parse_payload(row.get("raw_payload_json"))\n    source_id = str(row.get("source_record_id") or row["id"])\n    case_ref = first_text(payload, "case_ref", "raw_case_id", "case_id")\n    symbol = str(row.get("symbol") or first_text(payload, "symbol") or "UNKNOWN").upper()\n    layer = str(\n        first_text(payload, "structure_layer", "layer", "range_type", "type")\n        or row.get("range_type")\n        or ""\n    ).upper()\n    timeframe = row.get("timeframe") or first_text(\n        payload,\n        "timeframe",\n        "source_timeframe",\n        "chart_timeframe",\n    )\n    active = first_text(payload, "active_from_time")\n    high_time = first_text(payload, "range_high_time")\n    low_time = first_text(payload, "range_low_time")\n    raw_start = (\n        first_text(payload, "range_start_time", "start_time_utc", "start_time", "start")\n        or row.get("start_time_utc")\n    )\n    raw_end = (\n        first_text(payload, "range_end_time", "end_time_utc", "end_time", "end")\n        or row.get("end_time_utc")\n    )\n    formation = latest_time([high_time, low_time, active, raw_start])\n    span_start = earliest_time([high_time, low_time, active, raw_start])\n    span_end = latest_time([high_time, low_time, active, raw_start, raw_end])\n    effective_start = formation if layer == "WEEKLY" else span_start or formation\n\n    raw_range = RangeRow(\n        raw_id=int(row["id"]),\n        import_run_id=int(row["import_run_id"]),\n        source_record_id=source_id,\n        case_ref=case_ref,\n        symbol=symbol,\n        layer=layer,\n        timeframe=str(timeframe) if timeframe else None,\n        start_time=effective_start or active or raw_start,\n        end_time=span_end or raw_end,\n        high=number(\n            row.get("high"),\n            first_number(payload, "high", "range_high_price", "range_high", "rh"),\n        ),\n        low=number(\n            row.get("low"),\n            first_number(payload, "low", "range_low_price", "range_low", "rl"),\n        ),\n        status=(first_text(payload, "status", "range_status") or "ACTIVE").upper(),\n        inactive_from_time=first_text(payload, "inactive_from_time"),\n        explicit_parent_id=first_text(\n            payload,\n            "parent_range_id",\n            "parent_id",\n            "parent_source_record_id",\n        ),\n    )\n    return RangeSnapshot(raw_range, formation)\n\n\ndef load_latest_weekly_lifecycles',
    "snapshot_from_row",
)

marker = "\n\ndef clear_selected_relationships("
if marker not in text:
    raise RuntimeError("load_latest_relationships insertion marker missing")
text = text.replace(marker, '\ndef load_latest_relationships(\n    connection: sqlite3.Connection,\n) -> dict[str, sqlite3.Row]:\n    rows = connection.execute(\n        """\n        SELECT relationship.*\n        FROM parent_child_relationships AS relationship\n        JOIN (\n            SELECT child_range_id, MAX(id) AS max_id\n            FROM parent_child_relationships\n            WHERE relationship_type = ?\n            GROUP BY child_range_id\n        ) AS latest ON latest.max_id = relationship.id\n        WHERE relationship.relationship_type = ?\n        """,\n        (RELATIONSHIP_TYPE, RELATIONSHIP_TYPE),\n    ).fetchall()\n    return {\n        str(row["child_range_id"]): row\n        for row in rows\n        if row["child_range_id"] is not None\n    }\n' + marker, 1)

marker = "\n\ndef parse_time("
if marker not in text:
    raise RuntimeError("earliest_time insertion marker missing")
text = text.replace(marker, '\ndef earliest_time(values: list[str | None]) -> str | None:\n    parsed = [parse_time(value) for value in values if value]\n    parsed = [value for value in parsed if value is not None]\n    if not parsed:\n        return None\n    return canonical_time(min(parsed))\n' + marker, 1)

TARGET.write_text(text, encoding="utf-8")
